package org.obl.ldmapper
package builder

import scalaz.\/-
import shapeless._

trait HRead[H <: HList, ET] {
  def apply(h: H): LdDecode[ET]
}

object HRead {
  
  implicit lazy val toLdDecode0:HRead[HNil.type, Void]  = new HRead[HNil.type, Void] {
      def apply(h: HNil.type): LdDecode[Void] = LdDecode[Void] { m:JsonLdModel =>
        \/-(null.asInstanceOf[Void])
      }
    }

  def apply[H <: HList, ET](f: H => LdDecode[ET]) =
    new HRead[H, ET] {
      def apply(h: H): LdDecode[ET] = f(h)
    }

  type HType1[T1] = LdFieldDecode[T1] :: HNil.type
  type HType2[T1, T2] = LdFieldDecode[T2] :: HType1[T1]
  type HType3[T1, T2, T3] = LdFieldDecode[T3] :: HType2[T1, T2]
  type HType4[T1, T2, T3, T4] = LdFieldDecode[T4] :: HType3[T1, T2, T3]
  type HType5[T1, T2, T3, T4, T5] = LdFieldDecode[T5] :: HType4[T1, T2, T3, T4]
  type HType6[T1, T2, T3, T4, T5, T6] = LdFieldDecode[T6] :: HType5[T1, T2, T3, T4, T5]
  type HType7[T1, T2, T3, T4, T5, T6, T7] = LdFieldDecode[T7] :: HType6[T1, T2, T3, T4, T5, T6]
  type HType8[T1, T2, T3, T4, T5, T6, T7, T8] = LdFieldDecode[T8] :: HType7[T1, T2, T3, T4, T5, T6, T7]
  type HType9[T1, T2, T3, T4, T5, T6, T7, T8, T9] = LdFieldDecode[T9] :: HType8[T1, T2, T3, T4, T5, T6, T7, T8]
  type HType10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] = LdFieldDecode[T10] :: HType9[T1, T2, T3, T4, T5, T6, T7, T8, T9]
  type HType11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] = LdFieldDecode[T11] :: HType10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]
  type HType12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] = LdFieldDecode[T12] :: HType11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11]
  type HType13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] = LdFieldDecode[T13] :: HType12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12]
  type HType14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] = LdFieldDecode[T14] :: HType13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13]
  type HType15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] = LdFieldDecode[T15] :: HType14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14]
  type HType16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] = LdFieldDecode[T16] :: HType15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15]
  type HType17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] = LdFieldDecode[T17] :: HType16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16]
  type HType18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18] = LdFieldDecode[T18] :: HType17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17]
  type HType19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19] = LdFieldDecode[T19] :: HType18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18]
  type HType20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20] = LdFieldDecode[T20] :: HType19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19]
  type HType21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21] = LdFieldDecode[T21] :: HType20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20]
  type HType22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22] = LdFieldDecode[T22] :: HType21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21]
  
  implicit def toLdDecode1[T1] = apply[HType1[T1], T1] { h => LdDecode(h.head) }
  implicit def toLdDecode2[T1, T2] = apply[HType2[T1, T2], (T1, T2)] { h => LdDecode(h.tail.head, h.head) }
  implicit def toLdDecode3[T1, T2, T3] = apply[HType3[T1, T2, T3], (T1, T2, T3)] { h => LdDecode(h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode4[T1, T2, T3, T4] = apply[HType4[T1, T2, T3, T4], (T1, T2, T3, T4)] { h => LdDecode(h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode5[T1, T2, T3, T4, T5] = apply[HType5[T1, T2, T3, T4, T5], (T1, T2, T3, T4, T5)] { h => LdDecode(h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode6[T1, T2, T3, T4, T5, T6] = apply[HType6[T1, T2, T3, T4, T5, T6], (T1, T2, T3, T4, T5, T6)] { h => LdDecode(h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode7[T1, T2, T3, T4, T5, T6, T7] = apply[HType7[T1, T2, T3, T4, T5, T6, T7], (T1, T2, T3, T4, T5, T6, T7)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode8[T1, T2, T3, T4, T5, T6, T7, T8] = apply[HType8[T1, T2, T3, T4, T5, T6, T7, T8], (T1, T2, T3, T4, T5, T6, T7, T8)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode9[T1, T2, T3, T4, T5, T6, T7, T8, T9] = apply[HType9[T1, T2, T3, T4, T5, T6, T7, T8, T9], (T1, T2, T3, T4, T5, T6, T7, T8, T9)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10] = apply[HType10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11] = apply[HType11[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12] = apply[HType12[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13] = apply[HType13[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14] = apply[HType14[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15] = apply[HType15[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16] = apply[HType16[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17] = apply[HType17[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18] = apply[HType18[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19] = apply[HType19[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20] = apply[HType20[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21] = apply[HType21[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }
  implicit def toLdDecode22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22] = apply[HType22[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22], (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)] { h => LdDecode(h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.tail.head, h.tail.tail.tail.tail.head, h.tail.tail.tail.head, h.tail.tail.head, h.tail.head, h.head) }

}